CREATE TABLE IF NOT EXISTS Posts (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	user INT NOT NULL,
	image VARCHAR(100) NOT NULL,
	status VARCHAR(50),
	hashTag VARCHAR(50),
	likeCount INT NOT NULL DEFAULT 0,
	feedbackCount INT NOT NULL DEFAULT 0,
	createdDate DATETIME NOT NULL,
	FOREIGN KEY (user) REFERENCES Users(ID) ON DELETE NO ACTION
);