CREATE TABLE IF NOT EXISTS Likes (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	user INT NOT NULL,
	post INT NOT NULL,
	likeDate DATETIME ,
	FOREIGN KEY (user) REFERENCES Users(ID) ON DELETE NO ACTION,
	FOREIGN KEY (post) REFERENCES Posts(ID) ON DELETE NO ACTION
);