CREATE TABLE IF NOT EXISTS Users (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	displayName VARCHAR(50) NOT NULL,
	userName VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	imageProfile VARCHAR(100) NOT NULL,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	postsCount INT NOT NULL DEFAULT 0,
	followersCount INT NOT NULL DEFAULT 0,
	followingCount INT NOT NULL DEFAULT 0,
	createdDate DATETIME NOT NULL
);