CREATE TABLE IF NOT EXISTS Follows (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	followingUser INT NOT NULL,
	followedUser INT NOT NULL,
	followDate DATETIME NOT NULL,
	FOREIGN KEY (followingUser) REFERENCES Users(ID) ON DELETE NO ACTION,
	FOREIGN KEY (followedUser) REFERENCES Users(ID) ON DELETE NO ACTION
);