CREATE TABLE IF NOT EXISTS PasswordRecoveries (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	user INT NOT NULL,
	password varchar(50) NOT NULL,
	expirationDate DATETIME NOT NULL,
	FOREIGN KEY (user) REFERENCES Users(ID) ON DELETE NO ACTION
);