USE master

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='instagramDB')
DROP DATABASE instagramDB

CREATE DATABASE instagramDB

GO

IF OBJECT_ID('dbo.[Like]', 'U') IS NOT NULL 
DROP TABLE dbo.[Like];

IF OBJECT_ID('dbo.Follow', 'U') IS NOT NULL 
DROP TABLE dbo.Follow;

IF OBJECT_ID('dbo.Post', 'U') IS NOT NULL 
DROP TABLE dbo.Post;

IF OBJECT_ID('dbo.[User]', 'U') IS NOT NULL 
DROP TABLE dbo.[User];

GO

CREATE TABLE [User] (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	displayName NVARCHAR(50) NOT NULL,
	userName NVARCHAR(50) NOT NULL,
	email NVARCHAR(50) NOT NULL,
	[password] NVARCHAR(50) NOT NULL,
	imageProfile NVARCHAR(100) NOT NULL,
	firstName NVARCHAR(50) NOT NULL,
	lastName NVARCHAR(50) NOT NULL,
	postsCount INT NOT NULL DEFAULT 0,
	followersCount INT NOT NULL DEFAULT 0,
	followingCount INT NOT NULL DEFAULT 0,
	createdDate DATETIME NOT NULL DEFAULT GETDATE()
)

GO

CREATE TABLE Post (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	[user] INT FOREIGN KEY REFERENCES [USER](ID) ON DELETE NO ACTION,
	[image] NVARCHAR(100) NOT NULL,
	[status] NVARCHAR(50),
	hashTag NVARCHAR(50),
	likeCount INT NOT NULL DEFAULT 0,
	feedbackCount INT NOT NULL DEFAULT 0,
	createdDate DATETIME NOT NULL DEFAULT GETDATE()
)

GO

CREATE TABLE [Like] (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	[user] INT FOREIGN KEY REFERENCES [user](ID) ON DELETE NO ACTION,
	post INT FOREIGN KEY REFERENCES post(ID) ON DELETE NO ACTION,
	likeDate DATETIME NOT NULL DEFAULT GETDATE()
)

GO

CREATE TABLE Follow (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	followingUser INT FOREIGN KEY REFERENCES [user](ID) ON DELETE NO ACTION,
	followedUser INT FOREIGN KEY REFERENCES [user](ID) ON DELETE NO ACTION,
	followDate DATETIME NOT NULL DEFAULT GETDATE()
)

GO

